global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "pushgateway"
    static_configs:
      - targets: ["igorvpn.ru:9091"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["igorvpn.ru:9100"]
