global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "pushgateway-prod"
    static_configs:
      - targets: ["igorvpn.ru:9091"]

  - job_name: "node-exporter-prod"
    static_configs:
      - targets: ["igorvpn.ru:9100"]

  - job_name: "pushgateway-test"
    static_configs:
      - targets: ["test.igorvpn.ru:9091"]

  - job_name: "node-exporter-test"
    static_configs:
      - targets: ["test.igorvpn.ru:9100"]