{
 "title": "Online TEST",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Online",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "online{job=\"pushgateway-test\", exported_job=\"online_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "online{job=\"pushgateway-test\", exported_job=\"online_job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!=\"lo\", instance=\"test.igorvpn.ru:9100\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Входящий трафик",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "avg(rate(node_network_receive_bytes_total{device!=\"lo\", instance=\"test.igorvpn.ru:9100\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}