{
 "title": "Online PROD",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Online",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "online{job=\"pushgateway-prod\", exported_job=\"online_job\"}\nand max_over_time(online{job=\"pushgateway-prod\", exported_job=\"online_job\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "online{job=\"pushgateway-prod\", exported_job=\"online_job\"}\nand max_over_time(online{job=\"pushgateway-prod\", exported_job=\"online_job\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"igorvpn.ru:9100\",device!~\"^(lo|docker0|br-.*|veth.*)$\"}[5m]) * 8 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Входящий трафик",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"igorvpn.ru:9100\",device!~\"^(lo|docker0|br-.*|veth.*)$\"}[5m]) * 8 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}