apiVersion: 1

datasources:
  - name: Pushgateway
    type: prometheus
    access: proxy
    url: http://pushgateway:9091
    editable: true

  - name: Node Exporter
    type: prometheus
    access: proxy
    url: http://node-exporter:9100
    editable: true
    isDefault: true